### ISSUE TITLE
Enable mapping for Decompositions

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#422]
**Is your feature request related to a problem? Please describe.**
the `SpatialDecomp` class currently does not allow mapping, but with the creation of `MultipleGeoSeries`, it now can. 
**Describe the solution you'd like**
- [x] rename `SpatialDecomp` to `EigenDecomp`, spatialdecomp.py --> eigendecomp.py
- [x] in EigenDecomp.__init__, set locs = None
- [x] in EigenDecomp.modeplot(), code around `if locs is None`
- [x] expand MultipleGeoSeries.map() so that it can accept  `map(hue = loadings)`, where loadings is a numpy array of PCA weights, same length as self.seriest_list
^^ 05/25 Update: had to abandon this solution because Cartopy does not return proper axes that can be placed in a GridSpec framework; had to emulate the example of `GeoSeries.dashboard()` and code it by hand. 
There is now a working prototype of maps in `MultivarDecomp.modeplot()`. 

**TODO**:
- [x] write CI tests, particularly for the case where the object is MultipleSeries
- [x] flesh out docstrings for MultipleGeoSeries.map() and MultipleGeoSeries.pca() 
- [x] enable symbol mapping to archiveType ; currently, all markers are circles.

**Comment by CommonClimate** [comment]
Addressed in #435
